// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"ozon/internal/domain"
)

type CommentPage struct {
	Items       []*domain.Comment `json:"items"`
	EndCursor   *string           `json:"endCursor,omitempty"`
	HasNextPage bool              `json:"hasNextPage"`
}

type CreateCommentInput struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	Text     string  `json:"text"`
}

type CreatePostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Mutation struct {
}

type PostPage struct {
	Items       []*domain.Post `json:"items"`
	EndCursor   *string        `json:"endCursor,omitempty"`
	HasNextPage bool           `json:"hasNextPage"`
}

type Query struct {
}

type Subscription struct {
}
